### ISSUE TITLE
How can I Reobf ?

### ISSUE THREAD

**Issue by HowardZHY** [DxxxxY/mcp1.8.9op#3]
I ran recompile.bat but there's no Optifine files in temp/client_reobf or client_recomp.jar, and reobf/minecraft is empty.

**Comment by dxxxxy** [comment]
I would just build an artifact jar directly from the IDE. I never used recompile.

**Comment by HowardZHY** [comment]
you mean put the sources in a forge env?



At 2022-11-29 22:38:31, "DxxxxY" ***@***.***> wrote:

I would just build an artifact jar directly from the IDE. I never used recompile.

**Comment by dxxxxy** [comment]
> you mean put the sources in a forge env?
> 
> 
> 
> At 2022-11-29 22:38:31, "DxxxxY" ***@***.***> wrote:
> 
> I would just build an artifact jar directly from the IDE. I never used recompile.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

No, I mean simply package your project into a jar. In Intellij, you can build it using `Build artifact using module with dependencies`. I haven't build a client in a long time though.

**Comment by HowardZHY** [comment]
then how to reobf that jar



At 2022-11-30 00:03:25, "DxxxxY" ***@***.***> wrote:

you mean put the sources in a forge env?

At 2022-11-29 22:38:31, "DxxxxY" @.***> wrote:

I would just build an artifact jar directly from the IDE. I never used recompile.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

No, I mean simply package your project into a jar. In Intellij, you can build it using Build artifact using module with dependencies. I haven't build a client in a long time though.

**Comment by dxxxxy** [comment]
> then how to reobf that jar
> 
> 
> 
> At 2022-11-30 00:03:25, "DxxxxY" ***@***.***> wrote:
> 
> you mean put the sources in a forge env?
> 
> At 2022-11-29 22:38:31, "DxxxxY" @.***> wrote:
> 
> I would just build an artifact jar directly from the IDE. I never used recompile.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: @.***>
> 
> No, I mean simply package your project into a jar. In Intellij, you can build it using Build artifact using module with dependencies. I haven't build a client in a long time though.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

I don't know. Why do you want reobf so much? It wont reobf your source, only minecraft's which everyone already knows. It won't magically create mappings for your code.

**Comment by HowardZHY** [comment]
I wanna make notch-code mods



At 2022-11-30 02:15:26, "DxxxxY" ***@***.***> wrote:

then how to reobf that jar

At 2022-11-30 00:03:25, "DxxxxY" @.***> wrote:

you mean put the sources in a forge env?

At 2022-11-29 22:38:31, "DxxxxY" @.***> wrote:

I would just build an artifact jar directly from the IDE. I never used recompile.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

No, I mean simply package your project into a jar. In Intellij, you can build it using Build artifact using module with dependencies. I haven't build a client in a long time though.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @.***>

I don't know. Why do you want reobf so much? It wont reobf your source, only minecraft's which everyone already knows. It won't magically create mappings for your code.

**Comment by dxxxxy** [comment]
> I wanna make notch-code mods At 2022-11-30 02:15:26, "DxxxxY" ***@***.***> wrote: then how to reobf that jar At 2022-11-30 00:03:25, "DxxxxY" @.***> wrote: you mean put the sources in a forge env? At 2022-11-29 22:38:31, "DxxxxY" @.***> wrote: I would just build an artifact jar directly from the IDE. I never used recompile. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> No, I mean simply package your project into a jar. In Intellij, you can build it using Build artifact using module with dependencies. I haven't build a client in a long time though. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> I don't know. Why do you want reobf so much? It wont reobf your source, only minecraft's which everyone already knows. It won't magically create mappings for your code. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

This is for making clients, not mods. There is no forge environment.
