### ISSUE TITLE
1.8.9-natives missing

### ISSUE THREAD

**Issue by SeasonalFerret** [DxxxxY/mcp1.8.9op#4]
I'm attempting to follow the tutorial found [here](https://www.youtube.com/watch?v=hHBO6sp6NiI), but when I get to 3:29, it says to add 1.8.9-natives and the folder isn't there.

I'm unsure if it's related, but I'm getting this error when attempting to run setup.bat:

```
C:\Users\SylveonBottle\Downloads\mcp1.8.9op>setup.bat
Setup > Decompiling
== MCP 9.18 (data: 9.19, client: 1.8.9, server: 1.8.9) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
# found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
Looking in C:\Users\SylveonBottle\AppData\Roaming\.minecraft\versions for mc installs... OK
Copying assets... OK
Parsing JSON file... OK
Looking for minecraft main jar... Not found
Copying minecraft main jar... OK
> Checking libraries...
        Copying library jinput... OK
        Copying library lwjgl-platform... OK
        Copying library icu4j-core-mojang... OK
        Copying library twitch-external-platform... Error copying library tv.twitch:twitch-external-platform:4.5
Press any key to continue . . .
Setup > Fixing src
gc : Cannot find path
'C:\Users\SylveonBottle\Downloads\mcp1.8.9op\src\minecraft\net\minecraft\world\gen\structure\StructureMineshaftPieces.java'
because it does not exist.
At line:1 char:2
+ (gc src\minecraft\net\minecraft\world\gen\structure\StructureMineshaf ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\SylveonBottle\...haftPieces.java:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Out-File : Could not find a part of the path
'C:\Users\SylveonBottle\Downloads\mcp1.8.9op\src\minecraft\net\minecraft\world\gen\structure\StructureMineshaftPieces.java'.
At line:1 char:111
+ ... _1_', 'k' | Out-File -encoding ASCII src\minecraft\net\minecraft\worl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Setup > Recompiling
== MCP 9.18 (data: 9.19, client: 1.8.9, server: 1.8.9) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
!! Can not find client sources, try decompiling !!
!! Can not find server sources, try decompiling !!
Press any key to continue . . .
Setup > Removing mc src
The system cannot find the file specified.
The system cannot find the path specified.
Setup > Copying op src
op\Start.java
>>>>a bunch of .png and .java files
2951 File(s) copied
Setup > Done, should be OK
Press any key to continue . . .

```

**Comment by dxxxxy** [comment]
Yes, the first step fails at copying the Twitch library, and that step exits early, causing the source and natives to not be present for the other steps (such as fixing the source).

**Comment by dxxxxy** [comment]
I'm pretty sure that the natives and libraries are copied from your `.minecraft`, so try to launch a forge install from the Official Minecraft Launcher so that it can check all the natives and download those missing.

**Comment by SeasonalFerret** [comment]
Forge "grabbed 13 libraries" upon installation, and after first launch the project worked as intended.

I kindly ask that you remove the "invalid" tag, as it may draw those seeking a similar solution away from this thread as a proper fix.

**Comment by dxxxxy** [comment]
> Forge "grabbed 13 libraries" upon installation, and after first launch the project worked as intended.
> 
> 
> 
> I kindly ask that you remove the "invalid" tag, as it may draw those seeking a similar solution away from this thread as a proper fix.

The reason why I put the invalid tag is because there's nothing wrong with the repo itself. It's actually a very common action that needs to be done when installing a different version, for example, Forge (because client makers assume you already have natives, libraries, etc which helps to ship a single .jar. Also, I don't know why I asked you to run Forge 1.8.9 instead of just Vanilla 1.8.9 because this does not have forge stuff.

**Comment by SeasonalFerret** [comment]
> Also, I don't know why I asked you to run Forge 1.8.9 instead of just Vanilla 1.8.9 because this does not have forge stuff.

I had already ran 1.8.9 prior and it didn't work, after installing forge it did work.
I'm not quite sure how this logic works at all.

**Comment by dxxxxy** [comment]
> > Also, I don't know why I asked you to run Forge 1.8.9 instead of just Vanilla 1.8.9 because this does not have forge stuff.
> 
> I had already ran 1.8.9 prior and it didn't work, after installing forge it did work. I'm not quite sure how this logic works at all.

Well, the thing is that when you run a version in the MC Launcher, it will check hashes of libraries/natives and redownload those missing/wrong. But the thing missing was Twitch which should be in the Vanilla 1.8.9 version...

**Comment by SylveonBottle** [comment]
well how about this, is this caused by mcp decompiler or ?
![image](https://user-images.githubusercontent.com/17802843/232985716-9f34ea93-f235-4a5d-924c-f19445bf30ab.png)

**Comment by dxxxxy** [comment]
> well how about this, is this caused by mcp decompiler or ?
> 
> ![image](https://user-images.githubusercontent.com/17802843/232985716-9f34ea93-f235-4a5d-924c-f19445bf30ab.png)
> 
> 

Jesus christ. Ummm, to be honest I have no clue. Try to restart completely from step one and delete the cloned repo. This is the first time such an issue has been reported and the code to 1.8.9 has not been changed since MCP made this. If this is the only issue you can correct it.

**Comment by dxxxxy** [comment]
I'll check later today to make sure I also don't have this apocalypse.

**Comment by SylveonBottle** [comment]
> Try to restart completely from step one and delete the cloned repo. This is the first time such an issue has been reported and the code to 1.8.9 has not been changed since MCP made this. If this is the only issue you can correct it.

Started a new project, this issue did not occur.

**Comment by SeasonalFerret** [comment]
Issue #4 was caused by installing and launching Minecraft, then creating a new profile by 1.8.9 and launching it only a single time.

For some reason, after closing Minecraft and re-launching the launcher, an update was presented in which further files were downloaded. Despite Minecraft 1.8.9 launching successfully previously, mcp1.8.9op does not work unless you re-launch the Minecraft Launcher and let it update.

This shouldn't be an issue for users unless they use an alternative launcher (such as prism-launcher), and then install the vanilla launcher for the sole purpose of using it for mcp1.8.9op.
